botform/urls.py
from django.conf.urls import url, include

from .views import index_view, create_form_view, \
    manage_form_view, share_form_view, success_feedback_view

urlpatterns = [
    url(r'^', include([
        url(r'^$', index_view, name='index'),
        url(r'^create/$', create_form_view, name='create_form'),
        url(r'^(?P<pk>\d+)/manage/$', manage_form_view, name='manage_form'),
        url(r'^(?P<pk>\d+)/share/$', share_form_view, name='share_form'),
        url(r'^success/$', success_feedback_view, name='success'),
    ], namespace='form')),
]

botforms/urls.py
"""botform URL Configuration

"""
from django.conf.urls import url, include
from rest_framework import routers

from botform import api as form_api

router = routers.DefaultRouter()
router.register(r'forms', form_api.FormsViewSet)
router.register(r'submissions', form_api.SubmissionsViewSet)

urlpatterns = [
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/forms/(?P<pk>\d+)/details/?$', form_api.grid_details),
    url(r'^api/v1/forms/(?P<pk>\d+)/details/submission/?$', form_api.grid_submissions),
    url(r'^', include('botform.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

botform/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save

from .tasks import generate_pdf, notify_webhook

class Forms(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField(blank=True, null=True)
    schema = models.TextField(blank=True, null=True, help_text="JSON rep of the form schema")

    # PDF Output fields
    generate_pdf = models.BooleanField(default=False)
    pdf_output_template = models.TextField(blank=True, null=True)

    # Webhook url
    webhook_url = models.URLField(blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


class Submissions(models.Model):
    form = models.ForeignKey(Forms, related_name="submissions")
    data = models.TextField(blank=True, null=True, help_text="JSON rep of user input")
    pdf = models.URLField(max_length=400, blank=True, null=True, help_text='PDF Output URL')
    reference = models.CharField(max_length=45, blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

def on_new_submission(sender, instance, created, **kwargs):
    try:
        if created and instance.form.generate_pdf:
            submission_id = instance.pk
            generate_pdf.delay({'submission_id': submission_id})
            if instance.form.webhook_url:
                notify_webhook.delay({
                    'submission_id': submission_id,
                    'webhook_url': instance.form.webhook_url
                })
    except Exception as ex:
        print(str(ex))
post_save.connect(on_new_submission, sender=Submissions)

botform/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models  import Forms


@login_required()
def index_view(request):
    """
    Show form default page
    """
    forms = Forms.objects.all()
    return render(request, 'forms/index.html', {'forms': forms})

@login_required()
def create_form_view(request):
    """
    Add new form page
    """
    return render(request, 'forms/create.html',{})

@login_required()
def manage_form_view(request, pk):
    """
    Manage form page
    """
    return render(request, 'forms/manage.html',{})


def share_form_view(request, pk):
    """
    Open form page: Share form page
    """
    return render(request, 'forms/share.html',{})

def success_feedback_view(request):
    """
    Show success page on form save
    """
    return render(request, 'forms/success.html',{})

botform/templates/botform/create.html
{% extends 'base.html' %}

{% block content %}
{% verbatim %}
<div class="container" ng-app="formBuilder">
    <div class="row">
        <div class="col-md-12" ng-controller="formBuilderController">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Add form</h4>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">Title</label>
                        <input type="text" class="form-control" ng-model="form.title" required placeholder="ex. Order form">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Description</label>
                        <input type="text" class="form-control" ng-model="form.description" placeholder="Optional description">
                    </div>
                    <div class="form-designer">
                        <form-builder form="form.schema"></form-builder>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-default">
                                Cancel
                            </button>
                            <button class="btn btn-primary" ng-click="saveFormBtn()">
                                <i class="fa fa-check"></i> Save
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}
{% endblock %}

{% block extra_scripts %}
<script>
    angular.module("formBuilder", 
        [
            "ui.bootstrap", 
            "ui.select", 
            "formio", 
            "ngFormBuilder"
        ])
        .factory('formBuilderService', function ($http, $q, $rootScope) {
            return {
                createForm: function (payload) {
                    var deferred = $q.defer();
                    $http({
                        method: 'POST',
                        url: '/api/v1/forms/',
                        data: payload,
                        params: {format: 'json'}
                    }).then(function (response) {
                        deferred.resolve(response.data);
                    }).catch(function (err) {
                        deferred.reject(err);
                    });
                    return deferred.promise;
                }
            }
        })
        .controller('formBuilderController', 
            ["$scope", "formioComponents", "$timeout", "formBuilderService", 
                function($scope, formioComponents, $timeout, formBuilderService){
                    $scope.form = {
                        title: null,
                        description: null,
                        schema: {
                            components: [{}],
                            display: 'form',
                            _id: 1
                        }
                    };

                    // Save form
                    $scope.saveFormBtn = function() {
                        return formBuilderService.createForm($scope.form).then(function (res) {
                            alert('Saved')
                        }).catch(function (err) {
                            console.log(err);
                        });
                    }
                    
                }
            ]
        );
</script>
{% endblock %}

botform/templates/botform/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Forms list
                        <span class="pull-right">
                            <a href="{% url 'form:create_form' %}" class="btn btn-primary btn-sm">
                                <i class="fa fa-plus"></i> Add Form
                            </a>
                        </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Form</th>
                            </tr>
                        </thead>      
                        <tbody>
                            {% for form in forms%}
                            <tr>
                                <td>
                                    <a href="/">{{for.title}}</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td>
                                    No form found.
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

botform/templates/forms/create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% verbatim %}
<div class="container" ng-app="formBuilder" ng-cloak>
    <div class="row">
        <div class="col-md-12" ng-controller="formBuilderController">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Add form</h4>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label">Title</label>
                        <input type="text" class="form-control" ng-model="form.title" required placeholder="ex. Order form">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Description</label>
                        <input type="text" class="form-control" ng-model="form.description" placeholder="Optional description">
                    </div>
                    <div class="form-designer">
                        <form-builder form="form.schema"></form-builder>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="/" class="btn btn-default">
                                Cancel
                            </a>
                            <button class="btn btn-primary" ng-click="saveFormBtn()">
                                <i class="fa fa-check"></i> Save
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}
{% endblock %}

{% block extra_scripts %}
<script src="{% static 'js/form-builder.js' %}"></script>
{% endblock %}

botform/templates/forms/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Forms list
                        <span class="pull-right">
                            <a href="{% url 'form:create_form' %}" class="btn btn-primary btn-sm">
                                <i class="fa fa-plus"></i> Add Form
                            </a>
                        </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="col-md-6">Form</th>
                                <th class="col-md-3">Submissions</th>
                                <th class="col-md-3">Created</th>
                            </tr>
                        </thead>      
                        <tbody>
                            {% for form in forms%}
                            <tr>
                                <td>
                                    <a href="{% url 'form:manage_form' form.id %}">{{form.title}}</a>
                                </td>
                                <td>
                                    {{form.submissions.count}}        
                                </td>
                                <td>
                                    {{form.created_at|date:'d M Y'}}        
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td>
                                    No form found.
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

botform/templates/forms/manage.html
{% extends 'base.html' %}

{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'plugins/ng-formio-grid/dist/ng-formio-grid-full.min.css' %}">
{% endblock %}

{% block content %}
{% verbatim %}
<div class="container" ng-app="formManager" ng-cloak>
    <div class="row">
        <div class="col-md-12" ng-controller="formManagerController">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Manage form</h4>
                </div>
                <div class="panel-body" ng-init="getForm()">
                    <div>       
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#form-basic" aria-controls="form-basic" role="tab" data-toggle="tab">Form</a></li>
                            <li role="presentation"><a href="#submissions" aria-controls="submissions" role="tab" data-toggle="tab">Submissions</a></li>
                            <li role="presentation"><a href="#form-design" aria-controls="form-design" role="tab" data-toggle="tab">Design</a></li>
                            <li role="presentation"><a href="#notifications" aria-controls="notifications" role="tab" data-toggle="tab">Notification Settings</a></li>
                            <li role="presentation"><a href="#pdf-output" aria-controls="pdf-output" role="tab" data-toggle="tab">PDF Output</a></li>
                            <li role="presentation"><a href="#webhook" aria-controls="webhook" role="tab" data-toggle="tab">Webhook</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="form-basic">
                                <div class="row">
                                    <!-- Update form details -->
                                    <div class="col-md-6">
                                        <h4>Update form</h4>
                                        <form>
                                            <div class="form-group">
                                                <label class="control-label">Title</label>
                                                <input type="text" ng-model="form.title" class="form-control" required>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Description</label>
                                                <textarea rows="2" ng-model="form.description" class="form-control"></textarea>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <button class="btn btn-primary" ng-click="saveFormDetails()">
                                                        <i class="fa fa-check"></i> Save Changes
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>

                                    <!-- Publish links -->
                                    <div class="col-md-6">
                                        <h4>Publish and Share</h4>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <a href="{{share_url}}" target="_blank" class="btn btn-success">Share Form</a>
                                                <div class="help-block">
                                                    Append reference/tracking ID for external system e.g http://myformurl?reference=2
                                                    The reference value will be attached to the submission.
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <h3>Embend form to your website</h3>
                                                <pre>&lt;iframe frameBorder="0" src="{{share_url}}"&gt;&lt;/iframe&gt;</pre>
                                                <div class="help-block">
                                                    Copy-paste the snipset above where you would like to embend
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="submissions">
                                <formio-grid src="form_details_url"></formio-grid>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="form-design">
                                <div ng-if="form_schema">
                                    <div class="alert alert-warning">
                                        Changing form design may lead to data inconsistency incase submissions have already been made.
                                    </div>
                                    <form-builder form="form_schema"></form-builder>
                                    <!-- Save new form design -->
                                    <div class="row">
                                        <div class="col-md-12">
                                            <button class="btn btn-block btn-primary" ng-click="updateFormDesign()">
                                                <i class="fa fa-check"></i> Save Changes
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane" id="pdf-output">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" ng-model="generate_pdf"> Generate PDF for every submission
                                    </label>
                                </div>
                                <div class="row" ng-show="generate_pdf">
                                    <div class="col-md-12">
                                        <label class="control-label">Generated document template</label>
                                        <textarea ui-tinymce="tinymceOptions" ng-model="pdf_output_template"></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <button class="btn btn-block btn-primary" ng-click="updatePDFOutputSettings()">
                                            <i class="fa fa-check"></i> Save Changes
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane" id="webhook">
                                <div class="form-group">
                                    <label class="control-label">Webhook</label>
                                    <input type="text" ng-model="webhook_url" class="form-control" placeholder="Webhook URL where to send submission result">
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <button class="btn btn-block btn-primary" ng-click="updateWebhookSettings()">
                                            <i class="fa fa-check"></i> Save Changes
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}
{% endblock %}

{% block extra_scripts %}
<script src="{% static 'plugins/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'plugins/angular-ui-tinymce/dist/tinymce.min.js' %}"></script>
<script src="{% static 'plugins/ng-formio-grid/dist/ng-formio-grid-full.min.js' %}"></script>
<script src="{% static 'js/tinymce-options.js' %}"></script>
<script src="{% static 'js/form-manager.js' %}"></script>
{% endblock %}

botform/templates/forms/share.html
{% extends  'base.html' %}

{% load static %}

{% block menu %} {% endblock %}

{% block content %}
{% verbatim %}
<div class="container" ng-app="shareForm" ng-cloak>
    <div class="row">
        <div class="col-xs-12" ng-controller="shareFormController" ng-init="getForm()">
            <h1>{{form.title}}</h1>
            <div class="form-schema">
                <formio form="schema"></formio>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}
{% endblock %}

{% block extra_scripts %}
<script src="{% static 'js/share-form.js' %}"></script>
{% endblock %}

botform/templates/forms/success.html
{% extends  'base.html' %}

{% block menu %} {% endblock %}

{% block content %}
<div class="container success-page">
    <div class="row">
        <div class="col-xs-12">
            <h1>Saved</h1>
            <p>Form saved successful.</p>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

{% load static %}
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="theme/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Bot Forms</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Main CSS  Files   -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Form io files -->
    <!-- <link rel="stylesheet" href="{% static 'plugins/ng-tags-input/ng-tags-input.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/ng-dialog/css/ngDialog.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'plugins/ng-formio/dist/formio-complete.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/ng-formio-builder/dist/ngFormBuilder-complete.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/ng-notify/dist/ng-notify.min.css' %}">

    <!-- App CSS -->
    <link href="{% static 'css/app.css' %}" rel="stylesheet" />

    <!-- Extra page styles -->
    {% block extra_style %}{% endblock %}
</head>
<body>

<div class="wrapper">
    {% block menu %} {% include 'menu.html' %} {% endblock %}
    {% block content %}{% endblock %}
</div>

</body>
    <!-- Global CSRF Token -->
    {% csrf_token %}
    
    <!--   Theme JS Files   -->
    <script src="{% static 'plugins/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!--  Angular Plugins -->
    <script src="{% static 'plugins/file-saver.js/FileSaver.js' %}"></script>
    <script src="{% static 'plugins/moment/min/moment.min.js' %}"></script>

    <script src="{% static 'plugins/angular/angular.min.js' %}"></script>
    <!-- <script src="{% static 'plugins/angular-bootstrap/ui-bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/angular-ckeditor/angular-ckeditor.js' %}"></script>
    <script src="{% static 'plugins/angular-drag-and-drop-lists/angular-drag-and-drop-lists.min.js' %}"></script>
    <script src="{% static 'plugins/angular-file-saver/dist/angular-file-saver.min.js' %}"></script>
    <script src="{% static 'plugins/angular-moment/angular-moment.min.js' %}"></script>
    <script src="{% static 'plugins/angular-sanitize/angular-sanitize.min.js' %}"></script>
    <script src="{% static 'plugins/angular-ui-ace/ui-ace.min.js' %}"></script>
    <script src="{% static 'plugins/angular-ui-mask/dist/mask.min.js' %}"></script>
    <script src="{% static 'plugins/angular-ui-select/dist/select.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-ui-datetime-picker/dist/datetime-picker.min.js' %}"></script>
    <script src="{% static 'plugins/ng-dialog/js/ngDialog.min.js' %}"></script>
    <script src="{% static 'plugins/ng-file-upload/ng-file-upload.min.js' %}"></script>
    <script src="{% static 'plugins/ng-tags-input/ng-tags-input.min.js' %}"></script> -->

    <!-- Form IO Plugins -->
    <script src="{% static 'plugins/ng-formio/dist/formio-complete.min.js' %}"></script>
    <script src="{% static 'plugins/ng-formio-builder/dist/ngFormBuilder-complete.min.js' %}"></script>

    <!-- Other Plugins -->
    <script src="{% static 'plugins/ng-notify/dist/ng-notify.min.js' %}"></script>

    <!-- Main script -->
    <script src="{% static 'js/app.js' %}"></script>
    
    <!-- Add extra scripts -->
    {% block extra_scripts %}{% endblock %}

	<script type="text/javascript">
    	
	</script>

</html>

templates/menu.html
<nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Forms</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li class="active">
            <a href="{% url 'form:index' %}">
              Forms
            </a>
          </li>
          <li>
            <a href="#">Settings</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.email}} <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/accounts/logout">Log out</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>